# Generated by Django 4.1.5 on 2023-01-30 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("APP_Prueba_Backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pelicula",
            name="country",
        ),
        migrations.RemoveField(
            model_name="pelicula",
            name="location",
        ),
        migrations.RemoveField(
            model_name="pelicula",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="pelicula",
            name="title",
        ),
        migrations.AddField(
            model_name="pelicula",
            name="calificacion",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="titulo",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APP_Prueba_Backend.pelicula",
                    ),
                ),
            ],
        ),
    ]
