# Generated by Django 4.1.5 on 2023-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "APP_Prueba_Backend",
            "0002_remove_pelicula_country_remove_pelicula_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="pais",
            field=models.CharField(default="Desconocido", max_length=25),
        ),
    ]
