# Generated by Django 4.1.5 on 2023-01-30 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_Prueba_Backend", "0003_pelicula_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="calificacion",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="pais",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
